const state={walk:3,jog:0,run:1,sprint:0,sets:8,active:false,index:0,phase:0,remaining:180,interval:null};
const modes=['walk','jog','run','sprint'];
const $=id=>document.getElementById(id); const fmt=n=>String(n).padStart(2,'0');
const app=document.querySelector('.app-shell');
const spriteRunner=$('spriteRunner'); let spriteFrame=0, spriteTimer;
const walkFrames=Array.from({length:8},(_,i)=>`assets/user-run/frame-${i}.png`);const sprintFrames=Array.from({length:8},(_,i)=>`assets/user-fast/frame-${i}.png`);
function setSprite(mode){if(!spriteRunner)return;clearInterval(spriteTimer);spriteRunner.className=`sprite-runner sprite-${mode}`;let frame=0;const frames=mode==='run'||mode==='sprint'?sprintFrames:walkFrames;const show=()=>{spriteRunner.style.backgroundImage=`url("${frames[frame%frames.length]}")`;spriteRunner.style.backgroundPosition='center bottom'};show();const delay=mode==='sprint'?70:mode==='run'?88:mode==='jog'?108:138;spriteTimer=setInterval(()=>{frame++;show();spriteRunner.style.transform=`translateX(-50%) translateY(${Math.sin(Date.now()/180)*1.5}px) rotate(${mode==='sprint'?-3:mode==='run'?-2:0}deg)`},delay)}
function activeModes(){return modes.filter(m=>state[m]>0)}
function totalSeconds(){return activeModes().reduce((a,m)=>a+state[m]*60,0)*state.sets}
function setValues(){modes.forEach(m=>$(`${m}Value`).textContent=fmt(state[m]));$('setsValue').textContent=fmt(state.sets);$('setsPreview').textContent=fmt(state.sets);$('totalTime').textContent=`TOTAL ${fmt(Math.floor(totalSeconds()/60))}:${fmt(totalSeconds()%60)}`}
function update(){const list=activeModes();if(!list.length)return;const mode=list[state.phase%list.length];const next=list[(state.phase+1)%list.length];$('activeMode').textContent=mode.toUpperCase();$('nextMode').textContent=`${next.toUpperCase()} →`;$('sceneMode').textContent=`${mode.toUpperCase()}ING THE DISTANCE`;$('timeReadout').textContent=`${fmt(Math.floor(state.remaining/60))}:${fmt(state.remaining%60)}`;$('phaseCaption').textContent=`NEXT · ${next.toUpperCase()} ${fmt(state[next]*60/60)}:00`;$('setLabel').textContent=`SET ${fmt(state.index+1)} / ${fmt(state.sets)}`;$('runner').className=`runner runner-${mode}`;setSprite(mode);const max=state[mode]*60;const progress=1-state.remaining/max;$('dialProgress').style.strokeDashoffset=911*progress;$('dialProgress').style.stroke=mode==='walk'?'var(--lime)':mode==='jog'?'var(--cyan)':mode==='run'?'var(--orange)':'var(--pink)'}
function tick(){if(!state.active)return;state.remaining--;if(state.remaining<0){state.phase++;if(state.phase>=activeModes().length){state.phase=0;state.index++;if(state.index>=state.sets){finish();return}}state.remaining=state[activeModes()[state.phase]]*60}update()}
function finish(){clearInterval(state.interval);state.active=false;$('startButton').classList.remove('active');$('startButton').querySelector('span').textContent='START SESSION';$('sessionStatus').textContent='SESSION COMPLETE';$('footerHint').textContent='NICE WORK';$('timeReadout').textContent='00:00'}
document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const m=btn.dataset.mode;const d=btn.dataset.action==='plus'?1:-1;state[m]=Math.max(m==='sets'?1:0,Math.min(m==='sets'?99:60,state[m]+d));if(!state.active)setValues()}));
$('startButton').addEventListener('click',()=>{if(state.active){clearInterval(state.interval);state.active=false;$('startButton').querySelector('span').textContent='RESUME SESSION';$('sessionStatus').textContent='PAUSED';return}if(!activeModes().length)return;state.active=true;state.index=0;state.phase=0;state.remaining=state[activeModes()[0]]*60;app.classList.add('is-running');$('startButton').classList.add('active');$('startButton').querySelector('span').textContent='PAUSE SESSION';$('sessionStatus').textContent='IN PROGRESS';$('footerHint').textContent='KEEP MOVING';update();clearInterval(state.interval);state.interval=setInterval(tick,1000)});
$('backButton').addEventListener('click',()=>{clearInterval(state.interval);state.active=false;app.classList.remove('is-running');$('startButton').classList.remove('active');$('startButton').querySelector('span').textContent='START SESSION';$('sessionStatus').textContent='READY WHEN YOU ARE';$('footerHint').textContent='TAP START TO BEGIN'});
$('soundToggle').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='◖'?'◗':'◖'});setValues();update();
